// This code was autogenerated with `dbus-codegen-rust --client nonblock -f org.freedesktop.Notifications -d org.freedesktop.Notifications -p /org/freedesktop/Notifications`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::nonblock;

pub trait OrgFreedesktopNotifications {
    fn notify(
        &self,
        arg_0: &str,
        arg_1: u32,
        arg_2: &str,
        arg_3: &str,
        arg_4: &str,
        arg_5: Vec<&str>,
        arg_6: arg::PropMap,
        arg_7: i32,
    ) -> nonblock::MethodReply<u32>;
    fn close_notification(&self, arg_0: u32) -> nonblock::MethodReply<()>;
    fn get_capabilities(&self) -> nonblock::MethodReply<Vec<String>>;
    fn get_server_information(&self) -> nonblock::MethodReply<(String, String, String, String)>;
}

#[derive(Debug)]
pub struct OrgFreedesktopNotificationsNotificationClosed {
    pub arg_0: u32,
    pub arg_1: u32,
}

impl arg::AppendAll for OrgFreedesktopNotificationsNotificationClosed {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.arg_0, i);
        arg::RefArg::append(&self.arg_1, i);
    }
}

impl arg::ReadAll for OrgFreedesktopNotificationsNotificationClosed {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopNotificationsNotificationClosed {
            arg_0: i.read()?,
            arg_1: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopNotificationsNotificationClosed {
    const NAME: &'static str = "NotificationClosed";
    const INTERFACE: &'static str = "org.freedesktop.Notifications";
}

#[derive(Debug)]
pub struct OrgFreedesktopNotificationsActionInvoked {
    pub arg_0: u32,
    pub arg_1: String,
}

impl arg::AppendAll for OrgFreedesktopNotificationsActionInvoked {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.arg_0, i);
        arg::RefArg::append(&self.arg_1, i);
    }
}

impl arg::ReadAll for OrgFreedesktopNotificationsActionInvoked {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopNotificationsActionInvoked {
            arg_0: i.read()?,
            arg_1: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopNotificationsActionInvoked {
    const NAME: &'static str = "ActionInvoked";
    const INTERFACE: &'static str = "org.freedesktop.Notifications";
}

#[derive(Debug)]
pub struct OrgFreedesktopNotificationsActivationToken {
    pub arg_0: u32,
    pub arg_1: String,
}

impl arg::AppendAll for OrgFreedesktopNotificationsActivationToken {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.arg_0, i);
        arg::RefArg::append(&self.arg_1, i);
    }
}

impl arg::ReadAll for OrgFreedesktopNotificationsActivationToken {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopNotificationsActivationToken {
            arg_0: i.read()?,
            arg_1: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopNotificationsActivationToken {
    const NAME: &'static str = "ActivationToken";
    const INTERFACE: &'static str = "org.freedesktop.Notifications";
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgFreedesktopNotifications
    for nonblock::Proxy<'a, C>
{
    fn notify(
        &self,
        arg_0: &str,
        arg_1: u32,
        arg_2: &str,
        arg_3: &str,
        arg_4: &str,
        arg_5: Vec<&str>,
        arg_6: arg::PropMap,
        arg_7: i32,
    ) -> nonblock::MethodReply<u32> {
        self.method_call(
            "org.freedesktop.Notifications",
            "Notify",
            (arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6, arg_7),
        )
        .and_then(|r: (u32,)| Ok(r.0))
    }

    fn close_notification(&self, arg_0: u32) -> nonblock::MethodReply<()> {
        self.method_call(
            "org.freedesktop.Notifications",
            "CloseNotification",
            (arg_0,),
        )
    }

    fn get_capabilities(&self) -> nonblock::MethodReply<Vec<String>> {
        self.method_call("org.freedesktop.Notifications", "GetCapabilities", ())
            .and_then(|r: (Vec<String>,)| Ok(r.0))
    }

    fn get_server_information(&self) -> nonblock::MethodReply<(String, String, String, String)> {
        self.method_call("org.freedesktop.Notifications", "GetServerInformation", ())
    }
}
